### ISSUE TITLE
change mapping.yml

### ISSUE THREAD

**Issue by StevePain** [kartoza/docker-osm#96]
Hi there

I am trying to use docker-osm with the italian osm data.
But it seems i am unable to change the osm_buildings imported columns, even if i change the mapping.yml file, following the  example in 
https://github.com/kartoza/docker-osm-examples/blob/master/indonesia-buildings/docker-osm-settings/mapping.yml
But nothing seems to happen
the postgis schema of osm_buildings remains the same with the 5 columns: id, osm_id, name, type and geometry.

what am i doing wrong?

Thank you for your work
Steve

**Comment by Gustry** [comment]
Do you change the mapping file **before** the initial import?

**Comment by StevePain** [comment]
Thank you for replying

I run the docker-osm environment for the first time with the initial configuration.
Then changed the mapping.yml,
run make kill. Cleared containers and volumes. And then make run again

in particular... my mapping.yml is the same as seen in:
https://github.com/kartoza/docker-osm-examples/blob/master/indonesia-buildings/docker-osm-settings/mapping.yml

![dockerosm_mapping_file](https://user-images.githubusercontent.com/35501714/73595705-fbd9a600-451b-11ea-9a1f-40e55352c443.jpg)



but in the docker-osm project i still see osm_buildings as nothing was changed



![dockerosm_postgis_file](https://user-images.githubusercontent.com/35501714/73595774-86220a00-451c-11ea-93a1-c55ba288f2c4.jpg)

I dont know what im doing wrong
Steve

**Comment by NyakudyaA** [comment]
> Thank you for replying
> 
> I run the docker-osm environment for the first time with the initial configuration.
> Then changed the mapping.yml,
> run make kill. Cleared containers and volumes. And then make run again
> 
> in particular... my mapping.yml is the same as seen in:
> https://github.com/kartoza/docker-osm-examples/blob/master/indonesia-buildings/docker-osm-settings/mapping.yml
> 
> ![dockerosm_mapping_file](https://user-images.githubusercontent.com/35501714/73595705-fbd9a600-451b-11ea-9a1f-40e55352c443.jpg)
> 
> but in the docker-osm project i still see osm_buildings as nothing was changed
> 
> ![dockerosm_postgis_file](https://user-images.githubusercontent.com/35501714/73595774-86220a00-451c-11ea-93a1-c55ba288f2c4.jpg)
> 
> I dont know what im doing wrong
> Steve

Hi Steve,  if you look at the docker-compose it now automatically downloads the PBF, mapping file, etc. If you need to use the modified mapping file in `settings` make sure you change the docker-compose.yml to reflect so ie
```
imposm:
    image: kartoza/docker-osm:imposm-latest
    build: docker-imposm3
    container_name: dockerosm_imposm
    volumes:
      # These are sharable to other containers
      - ./settings:/home/settings
      - import_done:/home/import_done
      - import_queue:/home/import_queue
      - cache:/home/cache
    depends_on:
      db:
        condition: service_healthy
```
