### ISSUE TITLE
Something was updated, now it stopped to work at MacOS

### ISSUE THREAD

**Issue by seregasheypak** [kartoza/docker-osm#98]
Trying to run `db`
```
Add rule to pg_hba: 0.0.0.0/0
Add rule to pg_hba: replication replicator 
Setup master database
Initializing Postgres Database at /var/lib/postgresql/12/main
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locales
  COLLATE:  en_US.UTF-8
  CTYPE:    en_US.UTF-8
  MESSAGES: C
  MONETARY: C
  NUMERIC:  C
  TIME:     C
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: error: could not create directory "/var/lib/postgresql/12/main": Permission denied
creating directory /var/lib/postgresql/12/main ... Setup master database
Initializing Postgres Database at /var/lib/postgresql/12/main
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

initdb: error: could not create directory "/var/lib/postgresql/12/main": Permission denied
The database cluster will be initialized with locales
  COLLATE:  en_US.UTF-8
  CTYPE:    en_US.UTF-8
  MESSAGES: C
  MONETARY: C
  NUMERIC:  C
  TIME:     C
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /var/lib/postgresql/12/main ... 
```

**Comment by NyakudyaA** [comment]
> Trying to run `db`
> 
> ```
> Add rule to pg_hba: 0.0.0.0/0
> Add rule to pg_hba: replication replicator 
> Setup master database
> Initializing Postgres Database at /var/lib/postgresql/12/main
> The files belonging to this database system will be owned by user "postgres".
> This user must also own the server process.
> 
> The database cluster will be initialized with locales
>   COLLATE:  en_US.UTF-8
>   CTYPE:    en_US.UTF-8
>   MESSAGES: C
>   MONETARY: C
>   NUMERIC:  C
>   TIME:     C
> The default text search configuration will be set to "english".
> 
> Data page checksums are disabled.
> 
> initdb: error: could not create directory "/var/lib/postgresql/12/main": Permission denied
> creating directory /var/lib/postgresql/12/main ... Setup master database
> Initializing Postgres Database at /var/lib/postgresql/12/main
> The files belonging to this database system will be owned by user "postgres".
> This user must also own the server process.
> 
> initdb: error: could not create directory "/var/lib/postgresql/12/main": Permission denied
> The database cluster will be initialized with locales
>   COLLATE:  en_US.UTF-8
>   CTYPE:    en_US.UTF-8
>   MESSAGES: C
>   MONETARY: C
>   NUMERIC:  C
>   TIME:     C
> The default text search configuration will be set to "english".
> 
> Data page checksums are disabled.
> 
> creating directory /var/lib/postgresql/12/main ... 
> ```

Can you try to change the mount point to /var/lib/postgresql/data

**Comment by seregasheypak** [comment]
Thanks for your response,
it worked for me
```yaml
volumes:
  # osm-postgis-data:
  import_done:
  import_queue:
  cache:
  osm_settings:
    driver: local
    driver_opts:
      type: none
      device: $PWD/settings
      o: bind
  # pgadmin_data:

... omitted for brevity...
services:
  db:
 ... omitted for brevity...
    volumes:
      - ./postgres-data:/var/lib/postgresql # !

 pgadmin4:
    image: dpage/pgadmin4:4.16
    hostname: pgadmin4
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin # !
```
